server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**
        
        - id: menu-items-service
          uri: lb://restaurant-service
          predicates:
            - Path=/menu-items/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
        
        - id: health-check
          uri: http://localhost:${server.port}
          predicates:
            - Path=/health/**
          filters:
            - SetPath=/actuator/health

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
